<html>
  <head>
    <title>Kidtopia</title>
    <link rel="stylesheet" href="site.css">
    <link rel="icon" href="logo.png" type="image/png">
  </head>
  <body>
    <div class="normal content">
      <header>
        <nav>
          <div class="bar">
            <img class="si" src="logo.png" alt="Logo Kidtopia">
          </div>
        </nav>
      </header>

      <section class="body">
      </section> 
      <section class="wave">
      </section> 
      <section class="wave1">
      </section> 


    <div class="nightcontent">
      <div class="doorway_door door">
        <div class="door_side">
          <div class="door_pannel"></div>
          <div class="door_pannel"></div>
          <div class="door_pannel"></div>
          <div class="door_pannel"></div>
          <div class="door_handel"></div>
        </div>
      </div>
      <div class="door_side"></div>
    </div>
  </body>
</html>

